export const ARTICLES = [
  {
    id: 'a1',
    title: '5 Ways to Manage Anxiety',
    category: 'Anxiety',
    image: 'https://images.pexels.com/photos/3760263/pexels-photo-3760263.jpeg?auto=compress&cs=tinysrgb&w=500',
    readTime: '4 min read',
    body: [
      "Anxiety has a way of showing up uninvited — a tight chest before a meeting, a racing mind at 2am, a wave of dread that doesn't seem to match the moment. The good news is that anxiety is one of the most researched, most manageable experiences in mental health. You don't have to eliminate it completely to feel better; you just need a few reliable ways to bring it back down to a manageable level.",
      "The first tool is your breath. When anxiety spikes, your body shifts into a faster, shallower breathing pattern that actually feeds the anxious feeling. Slowing your exhale down — breathing in for four counts and out for six — signals to your nervous system that it's safe to relax. It won't erase the worry, but it takes the edge off enough to think clearly again.",
      "Second, name what's happening. Simply saying to yourself, 'this is anxiety, not danger' creates a small but important gap between you and the feeling. Psychologists call this defusion — you're no longer fused with the thought, you're observing it. That gap is where choice lives.",
      "Third, get specific about the worry. Vague anxiety ('everything feels off') is harder to work with than a named one ('I'm worried I said the wrong thing in that email'). Writing the worry down, even in a single sentence, often shrinks it. If there's a real action you can take, take the smallest possible version of it. If there isn't, naming it is often enough to loosen its grip.",
      "Fourth, move your body. A short walk, some stretching, or just standing up and shaking out your hands helps burn off the stress chemicals your body produces when anxious. You don't need a workout — two or three minutes of movement is often enough to shift your state.",
      "Finally, remember that anxiety tends to come in waves, not straight lines. It rises, peaks, and falls — usually faster than it feels like it will in the moment. Riding out the wave, rather than fighting it, is often the fastest way through it. And if anxiety is a frequent visitor rather than an occasional one, that's worth talking through with a counselor — you don't have to figure it out alone.",
    ],
  },
  {
    id: 'a2',
    title: 'Building Emotional Resilience',
    category: 'Resilience',
    image: 'https://images.pexels.com/photos/3755755/pexels-photo-3755755.jpeg?auto=compress&cs=tinysrgb&w=500',
    readTime: '5 min read',
    body: [
      "Resilience is often misunderstood as toughness — the ability to just push through hard things without being affected by them. In reality, resilience is closer to flexibility than toughness. Resilient people still feel the full weight of difficult moments; they've simply built habits that help them bend without breaking, and recover a little faster each time.",
      "One of the biggest building blocks of resilience is a sense of connection. People who weather hard seasons well are rarely doing it entirely alone — they have at least one person, or one space, where they can be honest about how things really are. That doesn't have to be a big support network; even one steady relationship makes a measurable difference.",
      "Another building block is perspective over time. In the middle of a hard week, it's easy to feel like the hard feeling is permanent. Resilient thinking holds two things at once: 'this is genuinely difficult right now' and 'this is not the whole story of my life.' Neither one cancels the other out.",
      "Resilience also grows through small, repeated acts of self-trust. Each time you get through something you weren't sure you could handle — a hard conversation, a stressful deadline, a low mood you didn't expect to lift — you build evidence for yourself that you're more capable than the anxious voice in your head suggests. Keeping even an informal record of these moments (a note, a journal entry) can be a genuine resource on harder days.",
      "It helps to separate what's in your control from what isn't. Spending energy trying to control the uncontrollable is exhausting and rarely resilience-building. Redirecting that same energy toward the handful of things you can actually influence — your response, your boundaries, your next small step — tends to restore a sense of agency much faster.",
      "Resilience isn't about never struggling. It's about having a few reliable anchors — people, perspectives, and small proven habits — that help you find your footing again after you've been knocked off it. Building those anchors before a crisis hits is one of the most valuable things you can do for your future self.",
    ],
  },
  {
    id: 'a3',
    title: 'The Power of Journaling',
    category: 'Self-care',
    image: 'https://images.pexels.com/photos/317355/pexels-photo-317355.jpeg?auto=compress&cs=tinysrgb&w=500',
    readTime: '4 min read',
    body: [
      "There's something almost deceptively simple about journaling: you sit with a blank page, and you write what's true. But that simple act does something surprisingly powerful — it moves a thought from the swirl of your mind onto something fixed and visible, where you can actually look at it rather than just be carried by it.",
      "One reason journaling helps is that it slows thinking down. Thoughts in your head move fast and loop easily; the same worry can replay ten times in ten minutes. Writing forces a pace — you can only write one sentence at a time — and that pace alone often brings clarity that racing thoughts can't.",
      "Journaling is also a private space with no audience. There's no one to impress, correct, or manage. That freedom lets you write things you might never say out loud, which is often exactly the material that needs the most air.",
      "You don't need a particular style to benefit. Some people do best with structured prompts ('what am I grateful for today', 'what's one thing I'm proud of this week'); others do best with unfiltered stream-of-consciousness writing, letting whatever comes out come out without editing. Both are valid — the value comes from consistency, not format.",
      "A useful habit is to journal at the same point in your day, even briefly — right after waking, or right before bed. Two or three sentences a day, done consistently, builds more insight over time than an occasional long entry. Over weeks and months, your own journal becomes a kind of mirror: you start to notice your own patterns, triggers, and what actually helps you feel better.",
      "If a blank page feels intimidating, start smaller than feels necessary — one sentence about how today felt is enough. The goal isn't a perfect entry. It's giving your thoughts somewhere to land outside of your own head, even for just a few minutes a day.",
    ],
  },
  {
    id: 'a4',
    title: 'Sleep & Mental Health',
    category: 'Sleep',
    image: 'https://images.pexels.com/photos/3771069/pexels-photo-3771069.jpeg?auto=compress&cs=tinysrgb&w=500',
    readTime: '5 min read',
    body: [
      "Sleep and mood are more tightly linked than most people realize — and the relationship runs in both directions. Poor sleep makes emotional regulation harder, and emotional distress makes sleep harder to come by. Understanding this loop is often the first step to breaking it.",
      "When you're sleep-deprived, your brain's emotional centers become more reactive while the parts responsible for calm, rational thinking become less effective. That's part of why everything feels a little more overwhelming after a bad night's sleep — it's not just in your head, it's measurable in how your brain is actually functioning that day.",
      "One of the most helpful (and least glamorous) tools for better sleep is consistency. Going to bed and waking up at roughly the same time every day — including weekends — trains your body's internal clock more effectively than almost anything else, including how many hours you sleep on any single night.",
      "The hour before bed matters more than people expect. Bright screens, stressful conversations, or intense scrolling right before sleep keep your nervous system activated exactly when it needs to be winding down. A simple wind-down routine — dimmer lights, a few minutes of stretching or reading, even just sitting quietly — signals to your body that it's safe to power down.",
      "If your mind tends to race the moment your head hits the pillow, it often helps to give those thoughts somewhere to go earlier in the evening — writing down tomorrow's to-do list, or jotting down whatever's looping in your head, well before bedtime. That way your brain doesn't have to hold onto it once you're trying to sleep.",
      "If sleep struggles are persistent — regularly taking a long time to fall asleep, waking frequently, or waking unrested despite enough hours in bed — it's worth mentioning to a professional rather than assuming it will resolve on its own. Sleep is foundational to mental health, not a side detail, and it deserves the same attention as any other part of your wellbeing.",
    ],
  },
  {
    id: 'a5',
    title: 'Mindful Movement',
    category: 'Exercise',
    image: 'https://images.pexels.com/photos/3822621/pexels-photo-3822621.jpeg?auto=compress&cs=tinysrgb&w=500',
    readTime: '4 min read',
    body: [
      "Mindful movement is the practice of paying attention to your body while it moves, rather than treating exercise as something to get through while your mind is somewhere else entirely. It's less about a specific type of activity and more about how present you are while doing it.",
      "Most of us are used to movement as a means to an end — burn calories, hit a step count, get it over with. Mindful movement flips that. The point isn't just what your body accomplishes, but what you notice along the way: your breath, the ground under your feet, the small sensations of muscles working.",
      "This kind of attention has a real calming effect. When your focus is fully on the present physical moment — the rhythm of a walk, the stretch of a muscle, the pattern of your breath — there's simply less mental space left over for anxious replaying or future-worrying. It's a form of grounding that happens to also be good for your body.",
      "You don't need a formal practice like yoga to benefit, although it's a great option if it appeals to you. A slow walk without your phone, gentle stretching in the morning, or even mindfully washing dishes while noticing the water and the motion of your hands all count. The common thread is attention, not intensity.",
      "If you're dealing with low motivation, low mood, or physical exhaustion, start smaller than you think you need to. Two minutes of gentle movement, done with attention, is more valuable than twenty minutes done on autopilot while your mind is elsewhere. Consistency in small doses beats occasional intensity almost every time.",
      "Over time, mindful movement becomes less of a task on a list and more of a check-in with yourself — a few minutes each day to notice how your body actually feels, rather than just what it needs to do next.",
    ],
  },
  {
    id: 'a6',
    title: 'Understanding Burnout',
    category: 'Stress',
    image: 'https://images.pexels.com/photos/3760067/pexels-photo-3760067.jpeg?auto=compress&cs=tinysrgb&w=500',
    readTime: '5 min read',
    body: [
      "Burnout isn't the same as being tired. Tiredness usually responds to rest — a good night's sleep, a weekend off, a vacation. Burnout is deeper: a state of chronic emotional, physical, and mental exhaustion caused by prolonged stress, and it often doesn't lift with a weekend off because the underlying cause hasn't changed.",
      "Burnout tends to show up in three recognizable ways: exhaustion that doesn't fully resolve with rest, a growing sense of cynicism or detachment from things you used to care about, and a creeping feeling of reduced effectiveness — like nothing you do feels like it's enough, or matters as much as it used to.",
      "It's easy to assume burnout only happens from work, but it can come from any sustained, unrelenting demand — caregiving, studying, parenting, or even the ongoing effort of managing a difficult personal situation. The common ingredient isn't the specific role, it's the mismatch between what's being asked of you and the resources (time, support, recovery) you actually have to meet it.",
      "One of the most important shifts in recovering from burnout is recognizing that the solution usually isn't 'try harder' or 'be more disciplined.' Those are exactly the strategies that led to burnout in the first place. Recovery tends to require the opposite: real reduction in demands, genuine rest (not just the absence of work, but activities that actually restore you), and often a hard look at boundaries that have been stretched too thin for too long.",
      "Small changes matter, but they work best alongside bigger ones. Taking real breaks during the day, protecting a non-negotiable amount of sleep, and reconnecting with something you enjoy purely for its own sake can all help — but if the underlying overload doesn't change, symptoms tend to return. Sometimes the most resilient thing you can do is have an honest conversation with the people around you about needing things to be different.",
      "If you're noticing the signs of burnout in yourself, that's worth taking seriously rather than pushing through. Talking it through with a counselor can help you separate what's genuinely fixable from what feels fixable but isn't, and build a realistic plan for recovery rather than white-knuckling through more of the same.",
    ],
  },
];

export const DAILY_QUOTES = [
  { text: "You don't have to be positive all the time. It's perfectly okay to feel sad, angry, annoyed, frustrated, scared, or anxious.", author: 'Lori Deschene' },
  { text: 'Mental health is not a destination, but a process. It\'s about how you drive, not where you\'re going.', author: 'Noam Shpancer' },
  { text: 'You are allowed to be both a masterpiece and a work in progress simultaneously.', author: 'Sophia Bush' },
  { text: "It's okay to not be okay. It's okay to ask for help.", author: 'Demi Lovato' },
  { text: "Owning our story and loving ourselves through that process is the bravest thing that we'll ever do.", author: 'Brené Brown' },
];
